# List of services with hourly rates
services = {
    'Cleaning': 25,    # $25 per hour
    'Gardening': 30,   # $30 per hour
    'Tutoring': 40     # $40 per hour
}

# Dictionary to track hours worked for each service
hours_worked = {
    'Cleaning': 0,
    'Gardening': 0,
    'Tutoring': 0
}

# Function to record hours worked for a service
def record_hours(service, hours):
    if service in hours_worked:
        hours_worked[service] += hours
        print(f"Recorded {hours} hour(s) for {service}.")
    else:
        print(f"Service {service} not found.")

# Function to calculate revenue for each service
def calculate_revenue():
    revenue = {}
    for service, hours in hours_worked.items():
        revenue[service] = hours * services[service]
    return revenue

# Function to find the service with the highest revenue
def top_revenue_service(revenue):
    top_service = max(revenue, key=revenue.get)
    return top_service, revenue[top_service]

# Example usage
record_hours('Cleaning', 5)
record_hours('Gardening', 3)
record_hours('Tutoring', 7)
record_hours('Cleaning', 2)

# Calculate revenue
revenue = calculate_revenue()

# Print the revenue generated by each service
print("\nRevenue Generated:")
for service, amount in revenue.items():
    print(f"{service}: ${amount:.2f}")

# Determine and print the top revenue-generating service
top_service, top_revenue = top_revenue_service(revenue)
print(f"\nTop Revenue-Generating Service: {top_service} (${top_revenue:.2f})")
